//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Visus.AddressValidation.Resources {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("Visus.AddressValidation.Resources.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        public static string Validation_Field_CannotBeNullOrEmpty {
            get {
                return ResourceManager.GetString("Validation_Field_CannotBeNullOrEmpty", resourceCulture);
            }
        }
        
        public static string Validation_Address_LinesCannotExceedThree {
            get {
                return ResourceManager.GetString("Validation_Address_LinesCannotExceedThree", resourceCulture);
            }
        }
        
        public static string Validation_Address_CountryNotSupported {
            get {
                return ResourceManager.GetString("Validation_Address_CountryNotSupported", resourceCulture);
            }
        }
        
        public static string Validation_Provider_CountryNotSupported {
            get {
                return ResourceManager.GetString("Validation_Provider_CountryNotSupported", resourceCulture);
            }
        }
        
        public static string Validation_Provider_OnlyValueSupportedInMode {
            get {
                return ResourceManager.GetString("Validation_Provider_OnlyValueSupportedInMode", resourceCulture);
            }
        }
        
        public static string Validation_Provider_OnlyValuesSupportedInMode {
            get {
                return ResourceManager.GetString("Validation_Provider_OnlyValuesSupportedInMode", resourceCulture);
            }
        }
        
        public static string Validation_Verification_ValueCouldNotBeVerified {
            get {
                return ResourceManager.GetString("Validation_Verification_ValueCouldNotBeVerified", resourceCulture);
            }
        }
        
        public static string Validation_Verification_RowValueCouldNotBeVerified {
            get {
                return ResourceManager.GetString("Validation_Verification_RowValueCouldNotBeVerified", resourceCulture);
            }
        }
    }
}
