namespace Visus.AddressValidation.SourceGeneration.Tests;

internal static class Constants
{
    public const string AutoGeneratedStatement = """
                                                 //------------------------------------------------------------------------------
                                                 // <auto-generated>
                                                 //     This code was generated by a tool.
                                                 //
                                                 //     Changes to this file may cause incorrect behavior and will be lost if
                                                 //     the code is regenerated.
                                                 // </auto-generated>
                                                 //------------------------------------------------------------------------------

                                                 """;
}
