//HintName: Visus_AddressValidation_SourceGeneration_Tests_ApiResponse_GetCustomResponseData.g.cs
// <auto-generated/>

#nullable enable annotations
#nullable disable warnings

using System.Collections.Generic;

namespace Visus.AddressValidation.SourceGeneration.Tests
{
    internal partial class ApiResponse
    {
        public IReadOnlyDictionary<string, object?> GetCustomResponseData()
        {
            return new Dictionary<string, object?>(StringComparer.OrdinalIgnoreCase)
            {
                ["responseId"] = ResponseId,
                ["response"] = ResponseText
            };
        }
    }
}