namespace Visus.AddressValidation.Integration.FedEx.Configuration;

using Microsoft.Extensions.Options;

/// <summary>
///     Validates <see cref="FedExServiceOptions" /> using the data annotation
///     attributes declared on its properties. This class is source-generated by
///     the <see cref="OptionsValidatorAttribute" />.
/// </summary>
[OptionsValidator]
public sealed partial class FedExServiceOptionsValidator : IValidateOptions<FedExServiceOptions>;
