namespace Visus.AddressValidation.SourceGeneration;

using System.Collections.Immutable;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using static Microsoft.CodeAnalysis.CSharp.SyntaxFactory;

/// <summary>
///     Provides Roslyn syntax-generation helpers used by the source generators.
/// </summary>
internal static class SyntaxGenerationHelpers
{
    /// <summary>
    ///     Prepends the standard <c>// &lt;auto-generated/&gt;</c> comment and a
    ///     <c>#nullable enable</c> directive to <paramref name="compilationUnit" />.
    /// </summary>
    /// <param name="compilationUnit">The compilation unit to annotate.</param>
    /// <returns>
    ///     A new <see cref="CompilationUnitSyntax" /> with the auto-generated header
    ///     added as leading trivia.
    /// </returns>
    internal static CompilationUnitSyntax AddAutoGeneratedHeader(CompilationUnitSyntax compilationUnit)
    {
        return compilationUnit.WithLeadingTrivia(
            TriviaList(
                Comment("// <auto-generated/>"),
                CarriageReturnLineFeed,
                CarriageReturnLineFeed,
                Trivia(
                    NullableDirectiveTrivia(
                            Token(TriviaList(Space), SyntaxKind.EnableKeyword, TriviaList(Space)),
                            true
                        )
                       .WithTargetToken(Token(SyntaxKind.AnnotationsKeyword))
                ),
                CarriageReturnLineFeed,
                Trivia(
                    NullableDirectiveTrivia(
                            Token(TriviaList(Space), SyntaxKind.DisableKeyword, TriviaList(Space)),
                            true
                        )
                       .WithTargetToken(Token(SyntaxKind.WarningsKeyword))
                ),
                CarriageReturnLineFeed,
                CarriageReturnLineFeed
            )
        );
    }

    /// <summary>
    ///     Builds a <see cref="ContainingTypeInfo" /> for the given <paramref name="type" />
    ///     by recursively capturing its containing type hierarchy.
    /// </summary>
    /// <param name="type">The named type symbol to describe.</param>
    /// <returns>
    ///     A <see cref="ContainingTypeInfo" /> populated with the type's name, fully-qualified
    ///     format, namespace, accessibility, and any parent containing types.
    /// </returns>
    internal static ContainingTypeInfo BuildContainingTypeInfo(INamedTypeSymbol type)
    {
        ImmutableArray<ContainingTypeInfo> parents = type.ContainingType is not null
                                                         ? [BuildContainingTypeInfo(type.ContainingType),]
                                                         : [];

        return new ContainingTypeInfo(
            type.Name,
            type.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat),
            type.ContainingNamespace.ToDisplayString(),
            type.DeclaredAccessibility,
            type.IsRecord,
            type.IsSealed,
            parents);
    }

    /// <summary>
    ///     Returns the <see cref="SyntaxToken" /> sequence that corresponds to the
    ///     given <paramref name="accessibility" /> modifier.
    /// </summary>
    /// <param name="accessibility">The Roslyn accessibility level to convert.</param>
    /// <returns>
    ///     An <see cref="IEnumerable{SyntaxToken}" /> of values representing the C# keyword(s)
    ///     for the given accessibility (e.g. <see langword="public" />, <c>protected internal</c>).
    ///     Returns an empty sequence for accessibility levels that have no corresponding
    ///     keyword (such as <see cref="Accessibility.NotApplicable" />).
    /// </returns>
    internal static IEnumerable<SyntaxToken> GetAccessibilityTokens(Accessibility accessibility)
    {
        return accessibility switch
        {
            Accessibility.Public => [Token(SyntaxKind.PublicKeyword),],
            Accessibility.Internal => [Token(SyntaxKind.InternalKeyword),],
            Accessibility.Private => [Token(SyntaxKind.PrivateKeyword),],
            Accessibility.Protected => [Token(SyntaxKind.ProtectedKeyword),],
            Accessibility.ProtectedOrInternal => [Token(SyntaxKind.ProtectedKeyword), Token(SyntaxKind.InternalKeyword),],
            _ => [],
        };
    }

    /// <summary>
    ///     Returns the full chain of <see cref="ContainingTypeInfo" /> records from the
    ///     outermost ancestor down to <paramref name="info" /> itself.
    /// </summary>
    /// <param name="info">The innermost <see cref="ContainingTypeInfo" /> to start from.</param>
    /// <returns>
    ///     A read-only list of <see cref="ContainingTypeInfo" /> ordered from the outermost
    ///     containing type to <paramref name="info" />, suitable for generating nested type
    ///     wrappers in source output.
    /// </returns>
    internal static IReadOnlyList<ContainingTypeInfo> GetTypeChain(ContainingTypeInfo info)
    {
        List<ContainingTypeInfo> chain = [];

        chain.AddRange(info.ContainingTypes.SelectMany(GetTypeChain));
        chain.Add(info);

        return chain;
    }
}
