namespace Visus.AddressValidation.Integration.Ups.Configuration;

using Microsoft.Extensions.Options;

/// <summary>
///     Validates <see cref="UpsServiceOptions" /> using the data annotation
///     attributes declared on its properties. This class is source-generated by
///     the <see cref="OptionsValidatorAttribute" />.
/// </summary>
[OptionsValidator]
public sealed partial class UpsServiceOptionsValidator : IValidateOptions<UpsServiceOptions>;
