namespace Visus.AddressValidation.Integration.Google.Configuration;

using Microsoft.Extensions.Options;

/// <summary>
///     Validates <see cref="GoogleServiceOptions" /> using the data annotation
///     attributes declared on its properties. This class is source-generated by
///     the <see cref="OptionsValidatorAttribute" />.
/// </summary>
[OptionsValidator]
public sealed partial class GoogleServiceOptionsValidator : IValidateOptions<GoogleServiceOptions>;
