namespace Visus.AddressValidation.Integration.PitneyBowes.Configuration;

using Microsoft.Extensions.Options;

/// <summary>
///     Validates <see cref="PitneyBowesServiceOptions" /> using the data annotation
///     attributes declared on its properties. This class is source-generated by
///     the <see cref="OptionsValidatorAttribute" />.
/// </summary>
[OptionsValidator]
public sealed partial class PitneyBowesServiceOptionsValidator : IValidateOptions<PitneyBowesServiceOptions>;
