//HintName: Visus.AddressValidation.SourceGeneration.Tests.Response.ApiData.g.cs
// <auto-generated/>
#pragma warning disable
#nullable enable
namespace Visus.AddressValidation.SourceGeneration.Tests
{
    /// <inheritdoc/>
    internal partial class Response
    {
        /// <inheritdoc/>
        private partial class ApiData
        {
            public IReadOnlyDictionary<string, object?> GetCustomResponseData()
            {
                return new Dictionary<string, object?>(StringComparer.OrdinalIgnoreCase)
                {
                    ["responseId"] = ResponseId,
                    ["response"] = ResponseText
                };
            }
        }
    }
}